# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "archive.local"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: psycopg2
  args:
    user: archive
    password: archivepass123
    database: synapse
    host: postgres
    cp_min: 5
    cp_max: 10
log_config: "/data/archive.local.log.config"
media_store_path: /data/media_store

# Allow unauthenticated access to media
enable_authenticated_media: false
registration_shared_secret: ".gA0.2rq.yFt2p.&0mF0cod9&n.:0fRyEiL=BHK-JRo~z3JeE&"
report_stats: false
macaroon_secret_key: "9il=jg9tK+_6_JV5tP7hw8@&m5eYujP;LLTYr_-:S#2hJ0@#Ga"
form_secret: "cOPk^u=QGq2stuZ@*teFcky6xUCYou^t0B~kTRQxtu1r5z_06Q"
signing_key_path: "/data/archive.local.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"

app_service_config_files:
  - /data/mautrix-meta-registration.yaml

# vim:ft=yaml